location ^~ /fe {
   proxy_pass http://host.docker.internal:3000;
   include site-config/proxy.conf;
}

location ^~ /api {
   proxy_pass http://host.docker.internal:4000;
   include site-config/proxy.conf;
}

location / {
   proxy_pass http://host.docker.internal:4000;
   include site-config/proxy.conf;
}

# location / {
#     default_type application/json;
#     include site-config/proxy.conf;
#     return 200 '{"welcome_to":"%domain%"}';
# }