import {
  functionalResponse,
  humanAuthForbiddenCaseLogFields,
  humanAuthIndependenceRule,
  humanAuthRequiredLogFields,
  humanAuthStep as step,
} from './human-auth-case-requirement-helpers.js';
import { humanAuthArtifactCaseRequirements } from './human-auth-recovery-case-requirements.js';

import type {
  DeferredHumanAuthCaseRequirement,
  HumanAuthCaseRequirement,
} from './human-auth-cases-contract.js';

const functionalAndSessionCases: readonly HumanAuthCaseRequirement[] = [
  {
    sentinelId: 'ST-42',
    profileIds: ['functional-enumeration'],
    controls: [
      step({
        id: 'valid-existing-login-control',
        boundary: 'raw-http',
        action: 'submit-login',
        target: 'synthetic-existing-identity',
        inputs: { identity: 'existing', password: 'valid-synthetic-password' },
        expectedFacts: { result: 'accepted', identityDisclosed: false },
        expectedPublicResponse: functionalResponse('valid-login-control'),
      }),
      step({
        id: 'existing-recovery-handler-control',
        boundary: 'raw-http',
        action: 'request-account-recovery',
        target: 'synthetic-existing-identity',
        inputs: { identity: 'existing' },
        expectedFacts: { result: 'generic-response', identityDisclosed: false },
        expectedPublicResponse: functionalResponse('recovery-enumeration-pair'),
      }),
    ],
    probes: [
      step({
        id: 'existing-invalid-login-response',
        controlId: 'valid-existing-login-control',
        boundary: 'raw-http',
        action: 'submit-login',
        target: 'synthetic-existing-identity',
        inputs: { identity: 'existing', password: 'invalid-synthetic-password' },
        expectedFacts: { result: 'rejected', identityDisclosed: false },
        expectedPublicResponse: functionalResponse('login-enumeration-pair'),
      }),
      step({
        id: 'absent-invalid-login-response',
        controlId: 'valid-existing-login-control',
        boundary: 'raw-http',
        action: 'submit-login',
        target: 'synthetic-absent-identity',
        inputs: { identity: 'absent', password: 'invalid-synthetic-password' },
        expectedFacts: { result: 'rejected', identityDisclosed: false },
        expectedPublicResponse: functionalResponse('login-enumeration-pair'),
      }),
      step({
        id: 'existing-recovery-response',
        controlId: 'existing-recovery-handler-control',
        boundary: 'raw-http',
        action: 'request-account-recovery',
        target: 'synthetic-existing-identity',
        inputs: { identity: 'existing' },
        expectedFacts: { result: 'generic-response', identityDisclosed: false },
        expectedPublicResponse: functionalResponse('recovery-enumeration-pair'),
      }),
      step({
        id: 'absent-recovery-response',
        controlId: 'existing-recovery-handler-control',
        boundary: 'raw-http',
        action: 'request-account-recovery',
        target: 'synthetic-absent-identity',
        inputs: { identity: 'absent' },
        expectedFacts: { result: 'generic-response', identityDisclosed: false },
        expectedPublicResponse: functionalResponse('recovery-enumeration-pair'),
      }),
    ],
    prohibitedSideEffects: [
      'identity-existence-disclosure',
      'authentication-with-invalid-credentials',
      'delivery-to-absent-identity',
    ],
    protectedStateKeys: ['account-state', 'session-state', 'unintended-mailbox'],
    requiredLogEvent: 'functional-enumeration-observation',
    requiredLogFields: humanAuthRequiredLogFields,
    forbiddenLogFields: humanAuthForbiddenCaseLogFields,
    recoveryExpectation: 'valid-existing-account-login-and-recovery-remain-available',
    independenceRule: humanAuthIndependenceRule,
  },
  {
    sentinelId: 'ST-43',
    profileIds: ['login-method-enforcement', 'failed-login-lockout-rate-limit'],
    controls: [
      step({
        id: 'enabled-login-method-control',
        boundary: 'raw-http',
        action: 'authenticate-with-enabled-method',
        target: 'synthetic-account',
        inputs: { method: 'configured-enabled', credential: 'valid' },
        expectedFacts: { result: 'accepted', sessionCreated: true },
        expectedPublicResponse: functionalResponse('enabled-method-control'),
      }),
      step({
        id: 'valid-password-login-control',
        boundary: 'raw-http',
        action: 'submit-password-login',
        target: 'synthetic-account',
        inputs: { limitKeyVariant: 'canonical', credential: 'valid' },
        expectedFacts: { result: 'accepted', sessionCreated: true },
        expectedPublicResponse: functionalResponse('valid-password-login-control'),
      }),
    ],
    probes: [
      step({
        id: 'disabled-password-method',
        controlId: 'enabled-login-method-control',
        boundary: 'raw-http',
        action: 'authenticate-with-enabled-method',
        target: 'synthetic-account',
        inputs: { method: 'configured-disabled-password', credential: 'valid' },
        expectedFacts: { result: 'method-disabled', sessionCreated: false },
        expectedPublicResponse: functionalResponse('method-disabled-rejection'),
      }),
      step({
        id: 'disabled-passwordless-method',
        controlId: 'enabled-login-method-control',
        boundary: 'raw-http',
        action: 'authenticate-with-enabled-method',
        target: 'synthetic-account',
        inputs: { method: 'configured-disabled-passwordless', credential: 'valid' },
        expectedFacts: { result: 'method-disabled', sessionCreated: false },
        expectedPublicResponse: functionalResponse('method-disabled-rejection'),
      }),
      step({
        id: 'canonical-failed-login',
        controlId: 'valid-password-login-control',
        boundary: 'raw-http',
        action: 'submit-password-login',
        target: 'synthetic-account',
        inputs: { limitKeyVariant: 'canonical', credential: 'invalid' },
        expectedFacts: { result: 'rejected', failureRecorded: true, sameLimitBudget: true },
        expectedPublicResponse: functionalResponse('generic-authentication-rejection'),
      }),
      step({
        id: 'equivalent-limit-key-variant',
        controlId: 'valid-password-login-control',
        boundary: 'raw-http',
        action: 'submit-password-login',
        target: 'synthetic-account',
        inputs: { limitKeyVariant: 'equivalent-public-input', credential: 'invalid' },
        expectedFacts: { result: 'rejected', failureRecorded: true, sameLimitBudget: true },
        expectedPublicResponse: functionalResponse('generic-authentication-rejection'),
      }),
      step({
        id: 'locked-account-valid-password',
        controlId: 'valid-password-login-control',
        boundary: 'raw-http',
        action: 'submit-password-login',
        target: 'synthetic-account',
        inputs: { accountState: 'locked', credential: 'valid' },
        expectedFacts: { result: 'locked', sessionCreated: false },
        expectedPublicResponse: functionalResponse('generic-authentication-rejection'),
      }),
      step({
        id: 'rate-limit-exhausted-variant',
        controlId: 'valid-password-login-control',
        boundary: 'raw-http',
        action: 'submit-password-login',
        target: 'synthetic-account',
        inputs: { limitState: 'exhausted', limitKeyVariant: 'equivalent-public-input' },
        expectedFacts: { result: 'throttled', sessionCreated: false, sameLimitBudget: true },
        expectedPublicResponse: functionalResponse('public-throttled-rejection'),
      }),
    ],
    prohibitedSideEffects: [
      'session-created-by-disabled-method',
      'session-created-while-locked',
      'failure-counter-bypassed',
      'rate-limit-budget-bypassed',
    ],
    protectedStateKeys: ['configured-login-policy', 'failed-login-counter', 'lockout-state'],
    requiredLogEvent: 'authentication-enforcement-rejection',
    requiredLogFields: humanAuthRequiredLogFields,
    forbiddenLogFields: humanAuthForbiddenCaseLogFields,
    recoveryExpectation: 'enabled-method-and-declared-lockout-recovery-remain-exact',
    independenceRule: humanAuthIndependenceRule,
  },
  {
    sentinelId: 'ST-44',
    profileIds: ['session-lifecycle'],
    controls: [
      step({
        id: 'anonymous-to-authenticated-renewal-control',
        boundary: 'browser',
        action: 'authenticate-session',
        target: 'browser-session',
        inputs: { initialState: 'anonymous', credential: 'valid' },
        expectedFacts: {
          result: 'accepted',
          sessionIdentifierChanged: true,
          authenticatedSessionCreated: true,
        },
        expectedPublicResponse: functionalResponse('authenticated-session-control'),
      }),
      step({
        id: 'active-session-use-control',
        boundary: 'browser',
        action: 'use-session',
        target: 'browser-session',
        inputs: { sessionState: 'active-authenticated' },
        expectedFacts: { result: 'allowed', protectedAccess: true },
        expectedPublicResponse: functionalResponse('active-session-control'),
      }),
    ],
    probes: [
      ...(['expired', 'logged-out', 'revoked'] as const).map((state) =>
        step({
          id: `${state}-session-reuse`,
          controlId: 'active-session-use-control',
          boundary: 'browser',
          action: 'use-session',
          target: 'browser-session',
          inputs: { sessionState: state },
          expectedFacts: { result: 'unauthenticated', protectedAccess: false },
          expectedPublicResponse: functionalResponse('terminated-session-rejection'),
        }),
      ),
    ],
    prohibitedSideEffects: [
      'anonymous-session-identifier-retained',
      'protected-state-access-by-terminated-session',
      'terminated-session-restored',
    ],
    protectedStateKeys: ['protected-account-state', 'terminated-session-state'],
    requiredLogEvent: 'session-lifecycle-rejection',
    requiredLogFields: humanAuthRequiredLogFields,
    forbiddenLogFields: humanAuthForbiddenCaseLogFields,
    recoveryExpectation: 'fresh-valid-authentication-creates-a-distinct-session',
    independenceRule: humanAuthIndependenceRule,
  },
  {
    sentinelId: 'ST-45',
    profileIds: ['cookie-csrf'],
    controls: [
      step({
        id: 'production-cookie-attributes-control',
        boundary: 'browser',
        action: 'inspect-production-cookie',
        target: 'host-only-session-cookie',
        inputs: { runtimeProfile: 'production-security' },
        expectedFacts: {
          secure: true,
          httpOnly: true,
          sameSite: 'declared-production-policy',
          hostOnly: true,
        },
        expectedPublicResponse: null,
      }),
      step({
        id: 'same-origin-valid-csrf-control',
        boundary: 'browser',
        action: 'submit-state-changing-request',
        target: 'csrf-protected-operation',
        inputs: { originContext: 'same-origin', csrfProof: 'valid' },
        expectedFacts: { result: 'allowed', mutationCount: 1 },
        expectedPublicResponse: functionalResponse('csrf-accepted-control'),
      }),
    ],
    probes: [
      step({
        id: 'same-origin-missing-csrf',
        controlId: 'same-origin-valid-csrf-control',
        boundary: 'browser',
        action: 'submit-state-changing-request',
        target: 'csrf-protected-operation',
        inputs: { originContext: 'same-origin', csrfProof: 'missing' },
        expectedFacts: { result: 'forbidden', mutationCount: 0 },
        expectedPublicResponse: functionalResponse('csrf-rejection'),
      }),
      step({
        id: 'same-origin-wrong-csrf',
        controlId: 'same-origin-valid-csrf-control',
        boundary: 'browser',
        action: 'submit-state-changing-request',
        target: 'csrf-protected-operation',
        inputs: { originContext: 'same-origin', csrfProof: 'wrong' },
        expectedFacts: { result: 'forbidden', mutationCount: 0 },
        expectedPublicResponse: functionalResponse('csrf-rejection'),
      }),
      step({
        id: 'cross-origin-same-site-csrf',
        controlId: 'same-origin-valid-csrf-control',
        boundary: 'browser',
        action: 'submit-state-changing-request',
        target: 'csrf-protected-operation',
        inputs: { originContext: 'cross-origin-same-site', csrfProof: 'missing' },
        expectedFacts: { result: 'forbidden', mutationCount: 0, cookieSending: 'policy-exact' },
        expectedPublicResponse: functionalResponse('csrf-rejection'),
      }),
      step({
        id: 'cross-site-loopback-ip-csrf',
        controlId: 'same-origin-valid-csrf-control',
        boundary: 'browser',
        action: 'submit-state-changing-request',
        target: 'csrf-protected-operation',
        inputs: { originContext: 'cross-site-loopback-ip', csrfProof: 'missing' },
        expectedFacts: { result: 'forbidden', mutationCount: 0, cookieSending: 'policy-exact' },
        expectedPublicResponse: functionalResponse('csrf-rejection'),
      }),
    ],
    prohibitedSideEffects: [
      'state-change-after-csrf-rejection',
      'cross-site-session-disclosure',
      'cookie-domain-widening',
    ],
    protectedStateKeys: ['csrf-protected-resource', 'session-cookie-policy'],
    requiredLogEvent: 'csrf-rejection',
    requiredLogFields: humanAuthRequiredLogFields,
    forbiddenLogFields: humanAuthForbiddenCaseLogFields,
    recoveryExpectation: 'fresh-valid-same-origin-csrf-proof-can-reach-the-operation',
    independenceRule: humanAuthIndependenceRule,
  },
];

/** Exact functional cases executed through the stable adapter seam. */
export const humanAuthCaseRequirements: readonly HumanAuthCaseRequirement[] = [
  ...functionalAndSessionCases,
  ...humanAuthArtifactCaseRequirements,
];

/** Deferred consistency requirement with no adapter or evidence path in the ordinary lane. */
export const deferredHumanAuthCaseRequirement: DeferredHumanAuthCaseRequirement = Object.freeze({
  sentinelId: 'ST-49',
  status: 'requirements-only-deferred',
  evidenceAllowed: false,
  invariant: 'concurrent duplicate consumption permits exactly one durable success',
  ordinaryScope: 'sequential-only',
  excludedMechanics: [
    'concurrent-consumption',
    'forced-race-barrier',
    'process-crash',
    'commit-boundary-interruption',
    'response-loss',
    'source-variation',
  ],
  expectedFutureOutcome:
    'one durable success, every competitor rejected, and no reusable intermediate artifact',
});
