CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION btree_gin;
CREATE EXTENSION unaccent;
DROP TABLE IF EXISTS sys_tenant CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;
DROP TABLE IF EXISTS sys_user_profile CASCADE;
DROP TABLE IF EXISTS sys_role CASCADE;
DROP TABLE IF EXISTS sys_user_role CASCADE;
DROP TABLE IF EXISTS sys_permission CASCADE;
DROP TABLE IF EXISTS sys_role_permission CASCADE;
DROP TABLE IF EXISTS sys_application CASCADE;
DROP TABLE IF EXISTS sys_client CASCADE;
DROP TABLE IF EXISTS sys_session CASCADE;
DROP TABLE IF EXISTS sys_access_token CASCADE;
DROP TABLE IF EXISTS sys_refresh_token CASCADE;
DROP TABLE IF EXISTS sys_mfa CASCADE;
DROP TABLE IF EXISTS sys_user_mfa CASCADE;
DROP TABLE IF EXISTS sys_key CASCADE;
CREATE TABLE sys_tenant();
ALTER TABLE sys_tenant ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_tenant ADD COLUMN name varchar NOT NULL;
ALTER TABLE sys_tenant ADD COLUMN database varchar NOT NULL;
ALTER TABLE sys_tenant ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_tenant ADD COLUMN allow_reset_password boolean  DEFAULT false;
ALTER TABLE sys_tenant ADD COLUMN allow_registration boolean  DEFAULT false;
ALTER TABLE sys_tenant ADD COLUMN organization varchar NOT NULL;
ALTER TABLE sys_tenant ADD PRIMARY KEY (id);
ALTER TABLE sys_tenant ADD UNIQUE (name);
ALTER TABLE sys_tenant ADD UNIQUE (database);
CREATE TABLE sys_user();
ALTER TABLE sys_user ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_user ADD COLUMN username varchar NOT NULL;
ALTER TABLE sys_user ADD COLUMN password varchar NOT NULL;
ALTER TABLE sys_user ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_user ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_user ADD COLUMN date_changed date  DEFAULT now();
ALTER TABLE sys_user ADD PRIMARY KEY (id);
ALTER TABLE sys_user ADD UNIQUE (username);
CREATE TABLE sys_user_profile();
ALTER TABLE sys_user_profile ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_user_profile ADD COLUMN email varchar;
ALTER TABLE sys_user_profile ADD COLUMN firstname varchar NOT NULL;
ALTER TABLE sys_user_profile ADD COLUMN lastname varchar NOT NULL;
ALTER TABLE sys_user_profile ADD COLUMN avatar varchar;
ALTER TABLE sys_user_profile ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_user_profile ADD COLUMN date_created date  DEFAULT now();
ALTER TABLE sys_user_profile ADD COLUMN date_changed date  DEFAULT now();
ALTER TABLE sys_user_profile ADD PRIMARY KEY (id);
CREATE TABLE sys_role();
ALTER TABLE sys_role ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_role ADD COLUMN role varchar NOT NULL;
ALTER TABLE sys_role ADD COLUMN description varchar;
ALTER TABLE sys_role ADD COLUMN role_type varchar  DEFAULT 'A';
ALTER TABLE sys_role ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_role ADD PRIMARY KEY (id);
ALTER TABLE sys_role ADD UNIQUE (role);
CREATE TABLE sys_user_role();
ALTER TABLE sys_user_role ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_user_role ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_user_role ADD COLUMN role_id uuid NOT NULL;
ALTER TABLE sys_user_role ADD PRIMARY KEY (id);
ALTER TABLE sys_user_role ADD UNIQUE (user_id,role_id);
CREATE TABLE sys_permission();
ALTER TABLE sys_permission ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_permission ADD COLUMN permission varchar NOT NULL;
ALTER TABLE sys_permission ADD COLUMN description varchar;
ALTER TABLE sys_permission ADD COLUMN application_id uuid NOT NULL;
ALTER TABLE sys_permission ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_permission ADD PRIMARY KEY (id);
ALTER TABLE sys_permission ADD UNIQUE (permission);
CREATE TABLE sys_role_permission();
ALTER TABLE sys_role_permission ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_role_permission ADD COLUMN role_id uuid NOT NULL;
ALTER TABLE sys_role_permission ADD COLUMN permission_id uuid NOT NULL;
ALTER TABLE sys_role_permission ADD PRIMARY KEY (id);
ALTER TABLE sys_role_permission ADD UNIQUE (role_id,permission_id);
CREATE TABLE sys_application();
ALTER TABLE sys_application ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_application ADD COLUMN logo varchar;
ALTER TABLE sys_application ADD COLUMN application_name varchar NOT NULL;
ALTER TABLE sys_application ADD COLUMN description varchar;
ALTER TABLE sys_application ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_application ADD PRIMARY KEY (id);
CREATE TABLE sys_client();
ALTER TABLE sys_client ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_client ADD COLUMN client_id varchar NOT NULL;
ALTER TABLE sys_client ADD COLUMN client_type varchar NOT NULL;
ALTER TABLE sys_client ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_client ADD COLUMN description varchar;
ALTER TABLE sys_client ADD COLUMN secret varchar  DEFAULT encode(digest(md5(random()::text), 'sha1'::text),'hex');
ALTER TABLE sys_client ADD COLUMN access_token_ttl integer;
ALTER TABLE sys_client ADD COLUMN refresh_token_ttl integer;
ALTER TABLE sys_client ADD COLUMN valid_from timestamp with time zone  DEFAULT now();
ALTER TABLE sys_client ADD COLUMN valid_until timestamp with time zone;
ALTER TABLE sys_client ADD COLUMN redirect_uri varchar;
ALTER TABLE sys_client ADD COLUMN client_credentials_user_id uuid;
ALTER TABLE sys_client ADD COLUMN application_id uuid NOT NULL;
ALTER TABLE sys_client ADD COLUMN post_logout_redirect_uri varchar;
ALTER TABLE sys_client ADD COLUMN is_back_channel_post_logout boolean  DEFAULT false;
ALTER TABLE sys_client ADD COLUMN is_system_client boolean  DEFAULT false;
ALTER TABLE sys_client ADD PRIMARY KEY (id);
ALTER TABLE sys_client ADD UNIQUE (client_id);
CREATE TABLE sys_session();
ALTER TABLE sys_session ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_session ADD COLUMN session_id varchar NOT NULL;
ALTER TABLE sys_session ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_session ADD COLUMN client_id uuid NOT NULL;
ALTER TABLE sys_session ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_session ADD PRIMARY KEY (id);
ALTER TABLE sys_session ADD UNIQUE (user_id,client_id);
CREATE TABLE sys_access_token();
ALTER TABLE sys_access_token ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_access_token ADD COLUMN ttl integer NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN refresh_ttl integer NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN auth_time integer NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_access_token ADD COLUMN auth_request_params jsonb;
ALTER TABLE sys_access_token ADD COLUMN access_token varchar  DEFAULT encode(digest(md5(random()::text), 'sha1'::text),'hex');
ALTER TABLE sys_access_token ADD COLUMN session_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN client_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN tenant_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD PRIMARY KEY (id);
ALTER TABLE sys_access_token ADD UNIQUE (access_token);
CREATE TABLE sys_refresh_token();
ALTER TABLE sys_refresh_token ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_refresh_token ADD COLUMN ttl integer NOT NULL;
ALTER TABLE sys_refresh_token ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_refresh_token ADD COLUMN refresh_token varchar  DEFAULT encode(digest(md5(random()::text), 'sha1'::text),'hex');
ALTER TABLE sys_refresh_token ADD COLUMN access_token_id uuid NOT NULL;
ALTER TABLE sys_refresh_token ADD PRIMARY KEY (id);
ALTER TABLE sys_refresh_token ADD UNIQUE (refresh_token);
CREATE TABLE sys_mfa();
ALTER TABLE sys_mfa ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_mfa ADD COLUMN name varchar NOT NULL;
ALTER TABLE sys_mfa ADD COLUMN settings jsonb;
ALTER TABLE sys_mfa ADD PRIMARY KEY (id);
CREATE TABLE sys_user_mfa();
ALTER TABLE sys_user_mfa ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_user_mfa ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_user_mfa ADD COLUMN mfa_id uuid NOT NULL;
ALTER TABLE sys_user_mfa ADD PRIMARY KEY (id);
CREATE TABLE sys_key();
ALTER TABLE sys_key ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_key ADD COLUMN key_type varchar NOT NULL;
ALTER TABLE sys_key ADD COLUMN key_id varchar NOT NULL;
ALTER TABLE sys_key ADD COLUMN data varchar NOT NULL;
ALTER TABLE sys_key ADD PRIMARY KEY (id);
ALTER TABLE sys_key ADD UNIQUE (key_id);
ALTER TABLE sys_user_profile ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user_role ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user_role ADD FOREIGN KEY (role_id) REFERENCES sys_role (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_permission ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_role_permission ADD FOREIGN KEY (role_id) REFERENCES sys_role (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_role_permission ADD FOREIGN KEY (permission_id) REFERENCES sys_permission (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_client ADD FOREIGN KEY (client_credentials_user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_client ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_session ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_session ADD FOREIGN KEY (client_id) REFERENCES sys_client (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (session_id) REFERENCES sys_session (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (client_id) REFERENCES sys_client (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (tenant_id) REFERENCES sys_tenant (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_refresh_token ADD FOREIGN KEY (access_token_id) REFERENCES sys_access_token (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user_mfa ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user_mfa ADD FOREIGN KEY (mfa_id) REFERENCES sys_mfa (id) ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX gin_sys_user_profile_user_id ON sys_user_profile USING GIN (user_id);
CREATE INDEX gin_sys_user_role_user_id ON sys_user_role USING GIN (user_id);
CREATE INDEX gin_sys_user_role_role_id ON sys_user_role USING GIN (role_id);
CREATE INDEX gin_sys_permission_application_id ON sys_permission USING GIN (application_id);
CREATE INDEX gin_sys_role_permission_role_id ON sys_role_permission USING GIN (role_id);
CREATE INDEX gin_sys_role_permission_permission_id ON sys_role_permission USING GIN (permission_id);
CREATE INDEX gin_sys_client_client_credentials_user_id ON sys_client USING GIN (client_credentials_user_id);
CREATE INDEX gin_sys_client_application_id ON sys_client USING GIN (application_id);
CREATE INDEX gin_sys_session_user_id ON sys_session USING GIN (user_id);
CREATE INDEX gin_sys_session_client_id ON sys_session USING GIN (client_id);
CREATE INDEX gin_sys_access_token_session_id ON sys_access_token USING GIN (session_id);
CREATE INDEX gin_sys_access_token_user_id ON sys_access_token USING GIN (user_id);
CREATE INDEX gin_sys_access_token_client_id ON sys_access_token USING GIN (client_id);
CREATE INDEX gin_sys_access_token_tenant_id ON sys_access_token USING GIN (tenant_id);
CREATE INDEX gin_sys_refresh_token_access_token_id ON sys_refresh_token USING GIN (access_token_id);
CREATE INDEX gin_sys_user_mfa_user_id ON sys_user_mfa USING GIN (user_id);
CREATE INDEX gin_sys_user_mfa_mfa_id ON sys_user_mfa USING GIN (mfa_id)