CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gin;
CREATE EXTENSION IF NOT EXISTS unaccent;
DROP TABLE IF EXISTS sys_tenant CASCADE;
DROP TABLE IF EXISTS sys_key CASCADE;
DROP TABLE IF EXISTS sys_application CASCADE;
DROP TABLE IF EXISTS sys_secret CASCADE;
DROP TABLE IF EXISTS sys_client CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;
DROP TABLE IF EXISTS sys_profile CASCADE;
DROP TABLE IF EXISTS sys_role CASCADE;
DROP TABLE IF EXISTS sys_permission CASCADE;
DROP TABLE IF EXISTS sys_user_role CASCADE;
DROP TABLE IF EXISTS sys_role_permission CASCADE;
DROP TABLE IF EXISTS sys_session CASCADE;
DROP TABLE IF EXISTS sys_application_session CASCADE;
DROP TABLE IF EXISTS sys_access_token CASCADE;
DROP TABLE IF EXISTS sys_refresh_token CASCADE;
DROP TABLE IF EXISTS sys_consent CASCADE;
DROP TABLE IF EXISTS sys_mfa CASCADE;
CREATE TABLE sys_tenant();
ALTER TABLE sys_tenant ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_tenant ADD COLUMN name varchar NOT NULL;
ALTER TABLE sys_tenant ADD COLUMN database varchar NOT NULL;
ALTER TABLE sys_tenant ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_tenant ADD COLUMN allow_reset_password boolean  DEFAULT false;
ALTER TABLE sys_tenant ADD COLUMN allow_registration boolean  DEFAULT false;
ALTER TABLE sys_tenant ADD COLUMN pw_change_first_login boolean  DEFAULT true;
ALTER TABLE sys_tenant ADD COLUMN auth_session_length_hours integer  DEFAULT 0;
ALTER TABLE sys_tenant ADD COLUMN organization varchar NOT NULL;
ALTER TABLE sys_tenant ADD PRIMARY KEY (id);
ALTER TABLE sys_tenant ADD UNIQUE (name);
ALTER TABLE sys_tenant ADD UNIQUE (database);
CREATE TABLE sys_key();
ALTER TABLE sys_key ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_key ADD COLUMN key_type varchar NOT NULL;
ALTER TABLE sys_key ADD COLUMN key_id varchar NOT NULL;
ALTER TABLE sys_key ADD COLUMN data varchar NOT NULL;
ALTER TABLE sys_key ADD PRIMARY KEY (id);
ALTER TABLE sys_key ADD UNIQUE (key_id);
CREATE TABLE sys_application();
ALTER TABLE sys_application ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_application ADD COLUMN logo varchar;
ALTER TABLE sys_application ADD COLUMN application_name varchar NOT NULL;
ALTER TABLE sys_application ADD COLUMN client_id varchar NOT NULL;
ALTER TABLE sys_application ADD COLUMN description varchar;
ALTER TABLE sys_application ADD COLUMN is_system boolean  DEFAULT false;
ALTER TABLE sys_application ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_application ADD COLUMN ow_consent boolean  DEFAULT false;
ALTER TABLE sys_application ADD COLUMN metadata jsonb  DEFAULT '{}';
ALTER TABLE sys_application ADD COLUMN tenant_id uuid NOT NULL;
ALTER TABLE sys_application ADD PRIMARY KEY (id);
ALTER TABLE sys_application ADD UNIQUE (client_id);
CREATE TABLE sys_secret();
ALTER TABLE sys_secret ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_secret ADD COLUMN secret varchar NOT NULL;
ALTER TABLE sys_secret ADD COLUMN description varchar;
ALTER TABLE sys_secret ADD COLUMN valid_from timestamp with time zone NOT NULL;
ALTER TABLE sys_secret ADD COLUMN valid_to timestamp with time zone NOT NULL;
ALTER TABLE sys_secret ADD COLUMN is_system boolean  DEFAULT false;
ALTER TABLE sys_secret ADD COLUMN application_id uuid NOT NULL;
ALTER TABLE sys_secret ADD PRIMARY KEY (id);
ALTER TABLE sys_secret ADD UNIQUE (secret,application_id);
CREATE TABLE sys_client();
ALTER TABLE sys_client ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_client ADD COLUMN client_type varchar  DEFAULT 'C';
ALTER TABLE sys_client ADD COLUMN redirect_uri varchar;
ALTER TABLE sys_client ADD COLUMN post_logout_redirect_uri varchar;
ALTER TABLE sys_client ADD COLUMN is_back_channel_post_logout boolean  DEFAULT false;
ALTER TABLE sys_client ADD COLUMN is_system boolean  DEFAULT false;
ALTER TABLE sys_client ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_client ADD COLUMN access_token_length integer NOT NULL;
ALTER TABLE sys_client ADD COLUMN refresh_token_length integer NOT NULL;
ALTER TABLE sys_client ADD COLUMN application_id uuid NOT NULL;
ALTER TABLE sys_client ADD COLUMN mfa_bypass_days integer  DEFAULT 0;
ALTER TABLE sys_client ADD COLUMN mfa_id uuid;
ALTER TABLE sys_client ADD PRIMARY KEY (id);
CREATE TABLE sys_user();
ALTER TABLE sys_user ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_user ADD COLUMN username varchar NOT NULL;
ALTER TABLE sys_user ADD COLUMN password varchar NOT NULL;
ALTER TABLE sys_user ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_user ADD COLUMN is_system boolean  DEFAULT false;
ALTER TABLE sys_user ADD COLUMN require_pw_change boolean  DEFAULT true;
ALTER TABLE sys_user ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_user ADD COLUMN date_modified timestamp with time zone  DEFAULT now();
ALTER TABLE sys_user ADD COLUMN service_application_id uuid;
ALTER TABLE sys_user ADD PRIMARY KEY (id);
ALTER TABLE sys_user ADD UNIQUE (username);
CREATE TABLE sys_profile();
ALTER TABLE sys_profile ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_profile ADD COLUMN email varchar;
ALTER TABLE sys_profile ADD COLUMN firstname varchar NOT NULL;
ALTER TABLE sys_profile ADD COLUMN lastname varchar NOT NULL;
ALTER TABLE sys_profile ADD COLUMN website varchar;
ALTER TABLE sys_profile ADD COLUMN zoneinfo varchar;
ALTER TABLE sys_profile ADD COLUMN birthdate varchar;
ALTER TABLE sys_profile ADD COLUMN gender varchar;
ALTER TABLE sys_profile ADD COLUMN middle_name varchar;
ALTER TABLE sys_profile ADD COLUMN locale varchar;
ALTER TABLE sys_profile ADD COLUMN avatar varchar;
ALTER TABLE sys_profile ADD COLUMN address varchar;
ALTER TABLE sys_profile ADD COLUMN postalcode varchar;
ALTER TABLE sys_profile ADD COLUMN city varchar;
ALTER TABLE sys_profile ADD COLUMN country varchar;
ALTER TABLE sys_profile ADD COLUMN state varchar;
ALTER TABLE sys_profile ADD COLUMN phone_number varchar;
ALTER TABLE sys_profile ADD COLUMN phone_number_verified boolean;
ALTER TABLE sys_profile ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_profile ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_profile ADD COLUMN user_state varchar;
ALTER TABLE sys_profile ADD COLUMN metadata jsonb  DEFAULT '{}';
ALTER TABLE sys_profile ADD COLUMN date_modified timestamp with time zone  DEFAULT now();
ALTER TABLE sys_profile ADD PRIMARY KEY (id);
CREATE TABLE sys_role();
ALTER TABLE sys_role ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_role ADD COLUMN role varchar NOT NULL;
ALTER TABLE sys_role ADD COLUMN description varchar;
ALTER TABLE sys_role ADD COLUMN is_system boolean  DEFAULT false;
ALTER TABLE sys_role ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_role ADD PRIMARY KEY (id);
ALTER TABLE sys_role ADD UNIQUE (role);
CREATE TABLE sys_permission();
ALTER TABLE sys_permission ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_permission ADD COLUMN permission varchar NOT NULL;
ALTER TABLE sys_permission ADD COLUMN description varchar;
ALTER TABLE sys_permission ADD COLUMN application_id uuid  DEFAULT null;
ALTER TABLE sys_permission ADD COLUMN is_system boolean  DEFAULT false;
ALTER TABLE sys_permission ADD COLUMN is_active boolean  DEFAULT true;
ALTER TABLE sys_permission ADD PRIMARY KEY (id);
CREATE TABLE sys_user_role();
ALTER TABLE sys_user_role ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_user_role ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_user_role ADD COLUMN role_id uuid NOT NULL;
ALTER TABLE sys_user_role ADD PRIMARY KEY (id);
ALTER TABLE sys_user_role ADD UNIQUE (user_id,role_id);
CREATE TABLE sys_role_permission();
ALTER TABLE sys_role_permission ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_role_permission ADD COLUMN role_id uuid NOT NULL;
ALTER TABLE sys_role_permission ADD COLUMN permission_id uuid NOT NULL;
ALTER TABLE sys_role_permission ADD PRIMARY KEY (id);
ALTER TABLE sys_role_permission ADD UNIQUE (role_id,permission_id);
CREATE TABLE sys_session();
ALTER TABLE sys_session ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_session ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_session ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_session ADD COLUMN last_token_auth_time timestamp with time zone  DEFAULT now();
ALTER TABLE sys_session ADD COLUMN date_expire timestamp with time zone NOT NULL;
ALTER TABLE sys_session ADD PRIMARY KEY (id);
CREATE TABLE sys_application_session();
ALTER TABLE sys_application_session ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_application_session ADD COLUMN application_id uuid NOT NULL;
ALTER TABLE sys_application_session ADD COLUMN session_id uuid NOT NULL;
ALTER TABLE sys_application_session ADD PRIMARY KEY (id);
CREATE TABLE sys_access_token();
ALTER TABLE sys_access_token ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_access_token ADD COLUMN date_expire timestamp with time zone NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN auth_time timestamp with time zone NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN ota varchar;
ALTER TABLE sys_access_token ADD COLUMN auth_request_params jsonb NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN token_reference varchar;
ALTER TABLE sys_access_token ADD COLUMN access_token varchar  DEFAULT encode(digest(md5(random()::text), 'sha1'::text),'hex');
ALTER TABLE sys_access_token ADD COLUMN session_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN client_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD COLUMN tenant_id uuid NOT NULL;
ALTER TABLE sys_access_token ADD PRIMARY KEY (id);
ALTER TABLE sys_access_token ADD UNIQUE (ota);
ALTER TABLE sys_access_token ADD UNIQUE (access_token);
CREATE TABLE sys_refresh_token();
ALTER TABLE sys_refresh_token ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_refresh_token ADD COLUMN date_expire timestamp with time zone NOT NULL;
ALTER TABLE sys_refresh_token ADD COLUMN date_created timestamp with time zone  DEFAULT now();
ALTER TABLE sys_refresh_token ADD COLUMN refresh_token varchar  DEFAULT encode(digest(md5(random()::text), 'sha1'::text),'hex');
ALTER TABLE sys_refresh_token ADD COLUMN access_token_id uuid NOT NULL;
ALTER TABLE sys_refresh_token ADD PRIMARY KEY (id);
ALTER TABLE sys_refresh_token ADD UNIQUE (refresh_token);
CREATE TABLE sys_consent();
ALTER TABLE sys_consent ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_consent ADD COLUMN is_consent boolean NOT NULL;
ALTER TABLE sys_consent ADD COLUMN scope varchar NOT NULL;
ALTER TABLE sys_consent ADD COLUMN application_id uuid NOT NULL;
ALTER TABLE sys_consent ADD COLUMN user_id uuid NOT NULL;
ALTER TABLE sys_consent ADD PRIMARY KEY (id);
ALTER TABLE sys_consent ADD UNIQUE (application_id,user_id);
CREATE TABLE sys_mfa();
ALTER TABLE sys_mfa ADD COLUMN id uuid NOT NULL DEFAULT uuid_generate_v4();
ALTER TABLE sys_mfa ADD COLUMN name varchar NOT NULL;
ALTER TABLE sys_mfa ADD COLUMN settings jsonb  DEFAULT '{}';
ALTER TABLE sys_mfa ADD PRIMARY KEY (id);
ALTER TABLE sys_mfa ADD UNIQUE (name);
ALTER TABLE sys_application ADD FOREIGN KEY (tenant_id) REFERENCES sys_tenant (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_secret ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_client ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_client ADD FOREIGN KEY (mfa_id) REFERENCES sys_mfa (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user ADD FOREIGN KEY (service_application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_profile ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_permission ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user_role ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_user_role ADD FOREIGN KEY (role_id) REFERENCES sys_role (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_role_permission ADD FOREIGN KEY (role_id) REFERENCES sys_role (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_role_permission ADD FOREIGN KEY (permission_id) REFERENCES sys_permission (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_session ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_application_session ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_application_session ADD FOREIGN KEY (session_id) REFERENCES sys_session (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (session_id) REFERENCES sys_session (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (client_id) REFERENCES sys_client (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_access_token ADD FOREIGN KEY (tenant_id) REFERENCES sys_tenant (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_refresh_token ADD FOREIGN KEY (access_token_id) REFERENCES sys_access_token (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_consent ADD FOREIGN KEY (application_id) REFERENCES sys_application (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_consent ADD FOREIGN KEY (user_id) REFERENCES sys_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX gin_sys_application_tenant_id ON sys_application USING GIN (tenant_id);
CREATE INDEX gin_sys_secret_application_id ON sys_secret USING GIN (application_id);
CREATE INDEX gin_sys_client_application_id ON sys_client USING GIN (application_id);
CREATE INDEX gin_sys_client_mfa_id ON sys_client USING GIN (mfa_id);
CREATE INDEX gin_sys_user_service_application_id ON sys_user USING GIN (service_application_id);
CREATE INDEX gin_sys_profile_user_id ON sys_profile USING GIN (user_id);
CREATE INDEX gin_sys_permission_application_id ON sys_permission USING GIN (application_id);
CREATE INDEX gin_sys_user_role_user_id ON sys_user_role USING GIN (user_id);
CREATE INDEX gin_sys_user_role_role_id ON sys_user_role USING GIN (role_id);
CREATE INDEX gin_sys_role_permission_role_id ON sys_role_permission USING GIN (role_id);
CREATE INDEX gin_sys_role_permission_permission_id ON sys_role_permission USING GIN (permission_id);
CREATE INDEX gin_sys_session_user_id ON sys_session USING GIN (user_id);
CREATE INDEX gin_sys_application_session_application_id ON sys_application_session USING GIN (application_id);
CREATE INDEX gin_sys_application_session_session_id ON sys_application_session USING GIN (session_id);
CREATE INDEX gin_sys_access_token_session_id ON sys_access_token USING GIN (session_id);
CREATE INDEX gin_sys_access_token_user_id ON sys_access_token USING GIN (user_id);
CREATE INDEX gin_sys_access_token_client_id ON sys_access_token USING GIN (client_id);
CREATE INDEX gin_sys_access_token_tenant_id ON sys_access_token USING GIN (tenant_id);
CREATE INDEX gin_sys_refresh_token_access_token_id ON sys_refresh_token USING GIN (access_token_id);
CREATE INDEX gin_sys_consent_application_id ON sys_consent USING GIN (application_id);
CREATE INDEX gin_sys_consent_user_id ON sys_consent USING GIN (user_id)