services:
    db:
        hostname: db
        container_name: porta_db
        image: postgres:14
        restart: unless-stopped
        ports:
            - 5010:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - TZ=Europe/Amsterdam
            - PGTZ=Europe/Amsterdam
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
            - ../temp/dev-db/:/var/lib/postgresql/data/
            - ../resources/database:/resources
    redis:
        image: redis:alpine
        container_name: porta_cache
        hostname: porta_cache
        command: redis-server --requirepass secret
        ports:
            - 16385:6379
    redis-commander:
        container_name: porta_redis_commander
        hostname: porta_redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:porta_cache:6379:0:secret
        ports:
            - "8081:8081"
