/**
 * Data export types for the Porta SDK.
 *
 * @module types/exports
 */

import type {
  PortabilityApplicationSelection,
  PortabilityCategory,
  PortabilityManifest,
  PortabilityScope,
} from './imports.js';

/** Closed administrative entity catalog supported by the export API. */
export type ExportEntityType = 'organizations' | 'clients' | 'users' | 'roles' | 'audit';

/** Public export representation. */
export type ExportFormat = 'csv' | 'json';

/** Exact scope and representation for one administrative export. */
export interface ExportParams {
  /** Supported entity catalog. */
  entityType: ExportEntityType;
  /** Output representation; defaults to JSON on the server. */
  format?: ExportFormat;
  /** Required tenant scope for users, clients, roles, and audit. */
  organizationId?: string;
  /** Required application relationship for role exports. */
  applicationId?: string;
  /** Required inclusive audit-window start. */
  startDate?: string;
  /** Required inclusive audit-window end. */
  endDate?: string;
}

/** Exact selection sent when exporting one portability manifest. */
export interface ExportManifestRequest {
  /** Organization or whole-environment source scope. */
  readonly scope: PortabilityScope;
  /** Non-empty manifest categories to include. */
  readonly categories: readonly PortabilityCategory[];
  /** Explicit application selection for application-related categories. */
  readonly application_selection: PortabilityApplicationSelection;
}

/** Parsed manifest attachment returned without writing to the local filesystem. */
export interface ExportManifestResponse {
  /** Strict manifest returned by Porta. */
  readonly manifest: PortabilityManifest;
  /** Safe final filename component suggested by Porta or generated by the SDK. */
  readonly filename: string;
}
