name: BuildTestDeploy
on:
    push:
        branches:
            - "master" # matches every branch that doesn't contain a '/'
            - "develop" # matches every branch containing a single '/'
            - "beta" # matches every branch
env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
    BuildTestDeploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: queue work
              if: always()
              run: work_queue queue ${{ github.event.organization.login }}_${{ github.event.repository.name }}

            - name: Installing Packages
              run: |
                  yarn install

            - name: Building the Project
              run: |
                  yarn build

            # - name: Testing the project
            #   run: |
            #       mv ./packages/webapi/docker/docker-compose-ci.yml ./packages/webapi/docker/docker-compose.yml
            #       yarn test

            - name: Publish Production Packages
              if: github.event_name == 'push' && contains(github.ref, 'refs/heads/master')
              run: |
                  git reset --hard
                  yarn tag-version-auto --yes
                  yarn publish-packages --yes

            - name: Publish Non-production Packages
              if: github.event_name == 'push' && contains(github.ref, 'refs/heads/develop')
              run: |
                  git reset --hard
                  yarn tag-version-auto --yes
                  yarn publish-packages-pre --yes --dist-tag next

            # - name: Deploy
            #   run: |
            #       ssh porta@docker1 "mkdir -p ~/containers/${BRANCH_NAME} && cd ~/containers/${BRANCH_NAME} && ./build-app-image.sh porta ${BRANCH_NAME} && ./swap.sh porta ${BRANCH_NAME}"

            - name: clear work
              if: always()
              run: work_queue clear ${{ github.event.organization.login }}_${{ github.event.repository.name }}
